"""Global constants for the document-semantic project."""

# --- Configuration Defaults ---

DEFAULT_CONFIG_PATHS = [
    "doc_semantic.yaml",
    "doc_semantic.yml",
    ".doc_semantic.yaml",
    ".doc_semantic.yml",
]

DEFAULT_PARSER = "python-docx"
DEFAULT_RECOGNIZER = "regex"
DEFAULT_VERBOSITY = "preview"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_PARALLEL_CHUNKS = 4

# --- Environment Variables ---

ENV_PARSER = "DOC_SEMANTIC_PARSER"
ENV_RECOGNIZER = "DOC_SEMANTIC_RECOGNIZER"
ENV_VERBOSITY = "DOC_SEMANTIC_VERBOSITY"
ENV_LOG_LEVEL = "DOC_SEMANTIC_LOG_LEVEL"
ENV_PARALLEL_CHUNKS = "DOC_SEMANTIC_PARALLEL_CHUNKS"

# --- External Services ---

ENV_MINERU_TOKEN = "MINERU_TOKEN"
ENV_MINERU_TOKEN_ALT = "token_mineru"
ENV_MINERU_CACHE_DIR = "MINERU_CACHE_DIR"
ENV_MINERU_PDF_CACHE_DIR = "MINERU_PDF_CACHE_DIR"
ENV_MINERU_SKIP_IMAGE_OCR = "MINERU_SKIP_IMAGE_OCR"


ENV_RECOGNIZER_MODEL_ID = "RECOGNIZER_MODEL_ID"
ENV_PROVIDER_BASE_URL = "PROVIDER_BASE_URL"
ENV_RECOGNIZER_MODEL_API_KEY = "RECOGNIZER_MODEL_API_KEY"
ENV_RECOGNIZER_MODELIZER_MODEL_TIMEOUT = "RECOGNIZER_MODELIZER_MODEL_TIMEOUT"
